### ISSUE TITLE
Version check issue

### ISSUE THREAD

**Issue by snatella** [starcitizen-lug/lug-helper#24]
I'm running on v1.11.1 but on startup I get:

```
The latest version of the LUG Helper is 
You are using v1.11.1

You can download new releases here:
https://github.com/the-sane/lug-helper/releases
```
No errors in the terminal though.

Ubu 20.04 if it's something obscure, not looked far into it myself yet.

**Comment by the-sane** [comment]
Our version checker is incredibly basic, simply doing a straight string compare. Doing math on version numbers with multiple dots seemed super complicated in bash last time I looked into it. 

Something probably went wrong when we migrated the repo here. I probably have to update a URL somewhere.

**Comment by the-sane** [comment]
Should be fixed with https://github.com/starcitizen-lug/lug-helper/commit/48d49dd438e5428ec5cec974aad19b65f1ceccc1

**Comment by snatella** [comment]
Oh my god how did I not notice that. Good catch!
