### ISSUE TITLE
no text in launcher following steps [Manjaro Latest]

### ISSUE THREAD

**Issue by bobstar3233** [starcitizen-lug/lug-helper#32]
![Screenshot from 2022-03-11 16-38-02](https://user-images.githubusercontent.com/15018376/157909473-96504a42-d9a6-4850-a9b3-5413d468bb59.png)

Photo for refrence

**Comment by Termuellinator** [comment]
just a guess, but maybe some wine-dependencies are missing?
Follow: https://github.com/lutris/docs/blob/master/WineDependencies.md
