### ISSUE TITLE
Only more recent wine-tkg Github action builds include the necessary stub patch for 3.17.1

### ISSUE THREAD

**Issue by jibsaramnim** [starcitizen-lug/lug-helper#38]
I'm fairly certain the just-released lug-helper update that adds the wine-tkg download option points to an outdated  (or, not frequently updated) version of wine-tkg that does not yet include the necessary stub for 3.17.1. I'm not entirely sure what kind of release cycle they follow, so this might be solved soon, but it might also take a while (it seems like the recent-most "release" build is 7.6 still, not 7.8.x).

Github does seem to have the necessary REST API endpoints to find and download these build artifacts ([here](https://docs.github.com/en/rest/actions/artifacts)), but it might require an additional system check (or just a question, I suppose), as there are [Arch](https://github.com/Frogging-Family/wine-tkg-git/actions/workflows/wine-arch.yml), [Fedora](https://github.com/Frogging-Family/wine-tkg-git/actions/workflows/wine-fedora.yml), and [Ubuntu](https://github.com/Frogging-Family/wine-tkg-git/actions/workflows/wine-ubuntu.yml) specific builds. 

I hope this helps!

**Edit:** Small addendum; if you do end up working with these build artifacts, note that at least for the Fedora variant I need to manually add the execute permission to all files within the `bin/` folder, or the runner won't be able to do its thing. I've not used the Arch or Ubuntu variants, so I'm not sure if the same is necessary there, but it might be worth a double check, just to be safe.

**Comment by Termuellinator** [comment]
You are correct, i wasn't aware the regular release-builds don't yet include the stub - my bad. I wanted to take a look if we can somehow add the nightly builds without creating a complete separate codepath for them - thanks for finding the documentation for the API! :)

We'd need to check how different distros work with the different builds though - and how we check for distros (as for examples variants like garuda won't have "Arch" in their naming in all cases...). Or if it's better to use the ubuntu variant for all.
Ananace is hosting patched builds, too - maybe i'll try to include those instead, if it's easier to implement. I can't promise when i'll find time to poke at it though.
Thanks for your findings in any case! :+1:

**Comment by Kribylet** [comment]
Based on jibsaramnim's info I was able to manually install the tkg runner in lutris from a scheduled artifact build (Ubuntu artifact for Linux Mint 21.3 in my case) and get star citizen to run. As he mentioned it was necessary to set file privs on the bin folder (`chmod --recurse +rx $dir`). In case anyone else having issues finds this, and for props :+1:

**Comment by zolfone** [comment]
I don't know if my issue is related to this, but I can't start SC with any wine version up to 7.6 due to EAC.
The launcher runs fine with other runners, I disabled EAC with lug-helper as per instructions, but when
the launcher starts the game I immediately receive an error from EAC saying "Settings.json not found",
the game exits and the launcher returns.
I tried with wine-tkg 7.6 runner provided by lug-helper but I can't even run the launcher with that runner,
on the console log I have an error saying "modify_ldt: operation not permitted".
Any suggestions are welcome, maybe you can point me where to download a wine-tkg 7.8 runner for
lutris to do more testing, if not I'll try to build one from source though I'm not that familiar in doing it.
Thanks!

**Comment by jibsaramnim** [comment]
> I don't know if my issue is related to this, but I can't start SC with any wine version up to 7.6 due to EAC.

Unfortunately what you're describing does not seem in any way related to what this issue is about, no. Tthis issue has nothing to do with EAC.

As a quick "thinking out loud" tip; try temporarily removing the hosts block, launch the game once and have it throw an EAC error (code 0 or 5 usually), then re-apply the hosts block, delete the `EasyAntiCheat` folder in your prefix' roaming folder (`/drive_c/users/$USER/AppData/Roaming/EasyAntiCheat`) and try again.

If that doesn't help, or if you need additionaln help with something, please join the [LUG Star Citizen Organization](https://robertsspaceindustries.com/orgs/LUG) and/or the [Discord](https://discord.gg/meCFYPj), there's a ton of real friendly folk there who can help you out :). This place here is probably best reserved for lug-helper related issues/fixes/improvements.

I hope this helps, and I hope to see you in the 'Verse!

**Comment by antiwesley** [comment]
`Downloading https://github.com/Frogging-Family/wine-tkg-git/releases/download/7.6.r12.g51472395/wine-tkg-staging-fsync-git-7.6.r12.g51472395-327-x86_64.pkg.tar.zst into /tmp/tmp.KTgdjGRBJw.lughelper/wine-tkg-staging-fsync-git-7.6.r12.g51472395-327-x86_64.pkg.tar.zst...

Extracting runner into /tmp/tmp.KTgdjGRBJw.lughelper/wine-tkg-staging-fsync-git-7.6.r12.g51472395-327-x86_64.pkg...
tar (child): zstd: Cannot exec: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now

Cleaning up /tmp/tmp.KTgdjGRBJw.lughelper/wine-tkg-staging-fsync-git-7.6.r12.g51472395-327-x86_64.pkg.tar.zst...
`
IMHO, until this is fixed, it's better to remove TKG as an option.

**Comment by antiwesley** [comment]
No, I didn't, and that did fix the issue, but it still stands that if the option to get newer builds that won't be usuable for every user, then it really shouldn't be there.

**Comment by Termuellinator** [comment]
Well, there are dependencies - if you don't have curl installed, no runner will install for instance.
But you are correct that it should be mentioned and i've already added zstd to the dependencies for the AUR pkgbuild :)

**Comment by the-sane** [comment]
Looks like I forgot to add zstd to the dependency checks at the top of the script when support for that type of compression was added. Whoops!

**Comment by Termuellinator** [comment]
I didn't think of that either ;)
I've added it in e7a3b30564d5e9904f38c2e5ad5e67ab805533d3 though.

**Comment by the-sane** [comment]
Closing, as this was handled by a dependency check.

Regardless, TKG has since moved to CI builds, which we don't currently support in the Helper so I've removed them from the list for now.
