### ISSUE TITLE
Remove molotov/snatella runners

### ISSUE THREAD

**Issue by snatella** [starcitizen-lug/lug-helper#39]
For the moment, as I've not got any wine runners that will work with the `SetThreadInformation` mine should probably be removed to avoid confusion.

```
diff --git a/lug-helper.sh b/lug-helper.sh
index 08b7564..8d55eaa 100755
--- a/lug-helper.sh
+++ b/lug-helper.sh
@@ -117,7 +117,6 @@ runners_dir="$data_dir/lutris/runners/wine"
 # ie. "RawFox" "https://api.github.com/repos/rawfoxDE/raw-wine/releases"
 runner_sources=(
     "RawFox" "https://api.github.com/repos/starcitizen-lug/raw-wine/releases"
-    "Molotov/Snatella" "https://api.github.com/repos/snatella/wine-runner-sc/releases"
     "/dev/null" "https://api.github.com/repos/gort818/wine-sc-lug/releases"
     "GloriousEggroll" "https://api.github.com/repos/GloriousEggroll/wine-ge-custom/releases"
     "TKG" "https://api.github.com/repos/Frogging-Family/wine-tkg-git/releases"

```

Or if you want add me to the repo and I will send a PR to remove it.

I will inevitably be back on the runner scene, but apart from part-time LUG admissions officer I'm not as heavily tech involved at the moment - there's plenty of better options for great runners at this time.

**Comment by the-sane** [comment]
I’m still on my backpacking trip and will be for a few more months, but I thought we had this repo set up so anyone can open a pull request? If something got changed, @Termuellinator can you please see what’s up with that when you have a moment? Thanks :)

Either way, this change makes sense to me until you resume your runner updates.
