### ISSUE TITLE
Adding referral codes

### ISSUE THREAD

**Issue by dirtbirb** [starcitizen-lug/lug-helper#43]
Are we able to add referral codes? I see they're hardcoded in there, can I submit a pull request just to add mine (STAR-WCHN-4ZMX) or did I miss the boat on that? Thanks!

**Comment by the-sane** [comment]
We can definitely get that added for you. I’m traveling so I’m probably a bit behind on our referral code Spectrum thread, but I’ll take care of yours right now!
