### ISSUE TITLE
Lutris Flatpak support

### ISSUE THREAD

**Issue by jibsaramnim** [starcitizen-lug/lug-helper#44]
It might be nice to add support for the Lutris flatpak installation too, now that that is out of beta. Do you think this is something that could fit within the scope of this utility?

Thanks so much for all that you've done! :)

**Comment by the-sane** [comment]
I'm not too familiar with flatpaks but, if we're going to support the flatpak install, these are the things we need to know:
1. How do we detect standard lutris vs flatpak lutris? Will `which lutris` be helpful here?
2. Does `command -v lutris` return the correct binary path for the flatpak install? We use this to detect if Lutris is installed on the system.
3. Does `pgrep lutris` find the flatpak install? We use this to detect whether Lutris is running and needs a restart. Likewise, will `pkill lutris` then terminate the flatpak Lutris gracefully? Or do flatpaks make this complicated?
4. What is the correct way to launch a detached flatpak application from the command line? For the standard install, we use `nohup lutris </dev/null &>/dev/null &`. A quick search shows that flatpak apps have to be launched by `flatpak run <app>`, is this the case with lutris?
6. Where are runners and dxvk versions stored on disk for the flatpak install?

Help answering these questions from someone using the flatpak install would be welcome. We'll also need testers if we're then able to implement this.

**Comment by jibsaramnim** [comment]
> Is it possible to have both versions of lutris installed at the same time?

I'm pretty sure there's nothing preventing you from installing both alongside one another yes, they live very much in their own respective areas so shouldn't clash :).

**Comment by Termuellinator** [comment]
The only other option i see would be to save it in our config files like the path to the game. I don't know how likely it is that someone would have both versions installed and if we want to cater to those edgecases though (i for example have both steam native and steam flatpak installed in case something doesn't work on flatpak).
Or we could copy the runners to both locations :thinking: 

`command -v` shouldn't work, as the binary-locations for flatpak aren't added to PATH. Checked with all my installed flatpaks and none showed an output. As the Flatpaks themself also have their own ENV i don't see how Lutris could do anything to add the flatpak'ed Binary to the PATH either...

**Comment by the-sane** [comment]
> Or we could copy the runners to both locations

This could work, good idea :+1: It'd be way simpler for users if we just handled both automatically.

**Comment by Termuellinator** [comment]
For the deletion it would be easy to do, too.
The interesting part starts when the user places runners in just one location manually :thinking:

**Comment by the-sane** [comment]
Huh, yeah. :thinking: Maybe we have to put a little indicator next to any downloads that only exist in one of the locations?
```
runner-in-both-places
runner-in-both-places
(f) runner-in-flatpak-only
runner-in-both-places
(n) runner-in-native-only
```

**Comment by Termuellinator** [comment]
That would complicate `download_select_delete()` a good bit compared to just put the folder list in an array though ^^
On the other hand, that would be the case for listing both directories anyway...

**Comment by the-sane** [comment]
Yeah, it's going to take a bit of array manipulation, but I think it's doable without too much hassle. I don't have any other simpler ideas.

**Comment by Termuellinator** [comment]
hm, we could also maybe create completely separate menu entries if one or the other is detected. So if both are present, we would have 'install runner to native' and 'install runner to flatpak' as well as 'delete runner form native' and 'delete runner from flatpak'?

**Comment by Vysp3r** [comment]
I know it's maybe not gonna help this thread, but I've been working on an app that do basically all of what lug-helper does, but using GTK and Vala for that. You can check it out [here](https://github.com/Vysp3r/ProtonPlus). I miss a couple of features, but from what I read here, it should have what you need.

**Comment by the-sane** [comment]
Adding a note here that the EAC workaround might also need to be adjusted to point to the correct path.

Which directory does the Flatpak Lutris use as its default to install new games into?

**Comment by jibsaramnim** [comment]
> Which directory does the Flatpak Lutris use as its default to install new games into?

I'm pretty sure it also defaults to `~/Games`. That's what it's set to on my system, and I'm fairly confident I did not customize this. Perhaps someone else can confirm if this is the case on their system too?

**Comment by the-sane** [comment]
Can I get some info on what the Flatpak Lutris looks like in `ps`?
`ps -ef | grep lutris`

This is how it showed up for one person:
`bwrap --args 41 lutris-wrapper`

If I'm looking for an automated way to tell which version of Lutris is currently running, can I grep for `lutris-wrapper` or will that show up differently on various systems/installs?

**Comment by Termuellinator** [comment]
for me, running flatpak lutris this yields `/usr/bin/python3 /app/bin/lutris` and `bwrap --args 42 lutris-wrapper`, while running repo-lutris yields `python3 /usr/bin/lutris`
That's on Arch - would be intersting if the python calls are this way on other distros, too?

**Comment by the-sane** [comment]
@Termuellinator Can you confirm that `pgrep lutris` and `pkill lutris` work for you with the flatpak install even though it shows up as two processes?

**Comment by Termuellinator** [comment]
funny enough, both only work for the flatpak version for me - never worked for the normal version :D

**Comment by the-sane** [comment]
Oooookay, so flatpak support is in. I need lots of help testing this as a fair bit of the download logic has changed.

Here's some things to try out:
- Starting the install process with native lutris, flatpak, and both installed (don't worry about fully installing it every time, that's outside the scope of the changes I've made)
- Does the install start fine regardless of whether the various versions of lutris are running? Does the Helper ask the right questions?
- Installing runners and dxvks with native, flatpak, and both lutrises installed
- Removing them, same scenarios
- What if the native/flatpak/both lutrises are running while doing this. Does the helper restart Lutris correctly each time?
- Repeat runner tests with GE, Rawfox, and devnull runners to make sure each source works (there's two slightly different sets of code depending on how the archives are packaged)
- Do the menus and console messages look good and make sense?
- Does the "Display helper/sc directories" option under the maintenance and troubleshoot menu show the correct runner/dxvk directories if both lutrises are installed?

Questions I still have:
- I'm not 100% positive I'm grepping for the right flatpak lutris process. I'm currently grepping for `lutris-wrapper`, but wondering if I should instead grep for `/app/bin/lutris`

**Comment by the-sane** [comment]
@Termuellinator  Looks like we have to change where we install the json and logo file to. Because flatpak. :man-facepalming: We have to put these somewhere in the home directory it seems, which I don't love, or temporarily copy them there so the flatpak lutris can see them. Any thoughts on how we should handle this?

**Comment by the-sane** [comment]
Update: I may have found a way to just forward the file to the flatpak: https://github.com/starcitizen-lug/lug-helper/commit/7d342416f7fd7a0175cc0542bd361ab7ddd1a8f5

**Comment by Termuellinator** [comment]
As lutris flatpak doesn't request any really fitting paths by default, i'd suggest `~/.var/app/net.lutris.Lutris/config/lutris/`
Or the folder for the prefix. Other than that we would need to modify the overrides for flatpak.
I'll take a look at your changes tomorrow, but thanks for the effort! :)

**Comment by jibsaramnim** [comment]
I don't have Lutris native installed so can't do the specific tests you've asked about, but with just the flatpak install, I can confirm that it correctly downloads and places GE's runners, and also correctly spots my already installed dxvk-async. For testing I also installed a slightly older version of dxvk-async while Lutris was running, and it correctly noticed that and also successfully restarted it. Very nice!

**Comment by the-sane** [comment]
We're nearing final release, but I still need extra eyeballs on this

Please test:
- Starting the install process with native lutris, flatpak, and both installed (don't worry about fully installing it every time, that's outside the scope of the changes I've made)
- Does the install start fine regardless of whether the various versions of lutris are running?
- Installing runners and dxvks with native, flatpak, and both lutrises installed
- Removing them, same scenarios
- What if the native/flatpak/both lutrises are running while doing this. Does the helper restart Lutris correctly each time?
- Does the "Display helper/sc directories" option under the maintenance and troubleshoot menu show the correct runner/dxvk directories?

**Comment by Termuellinator** [comment]
Looks good to me so far, haven't seen any issues.
Flatpak is recognized, gets runners installed, is displayed for the directories and so on.
Nice work! :D

**Comment by PureTryOut** [comment]
Everything seems to work except the menu for the `/dev/null` Wine runner.

```
Your glibc version is incompatible with the selected runner.

System glibc: v
Minimum required glibc: v2.33
```

I can't test the non-Flatpak scenario though, my system doesn't use glibc and doesn't do multilib, so a "native" install is out of the quesiton.

**Comment by the-sane** [comment]
@PureTryOut Thanks for testing it! This is actually really helpful as it's a scenario nobody else has reported. So does that mean the Lutris flatpak bundles its own glibc for these runners? Are you able to check which version it is on your install?

**Comment by Termuellinator** [comment]
I can't see that my flatpak'd lutris provides it's own glibc, but if it did, it should probably be in `~/.local/share/flatpak/app/net.lutris.Lutris/current/active/files/lib/` or `~/.local/share/flatpak/app/net.lutris.Lutris/current/active/files/lib32/` i guess?

**Comment by PureTryOut** [comment]
Flatpak bundles it's own yes. My host system doesn't have glibc but the container definitely does.

You can check what version with `flatpak run --command="ldd" net.lutris.Lutris --version`.

```
$ ldd --version
musl libc (x86_64)
Version 1.2.3
Dynamic Program Loader
Usage: /lib/ld-musl-x86_64.so.1 [options] [--] pathname
$ flatpak run --command="ldd" net.lutris.Lutris --version
ldd (GNU libc) 2.33
Copyright (C) 2021 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.
```

**Comment by the-sane** [comment]
Pushed some fixes to master.
@PureTryOut @Termuellinator Can you both please double check that it works on your ends?

You can change the version requirements in this line to trigger the warning message for testing:
https://github.com/starcitizen-lug/lug-helper/blob/6899d3d94b9977eb2460249be04973d230bc3ab5/lug-helper.sh#L1287

**Comment by PureTryOut** [comment]
Yup, works fine now!

**Comment by Termuellinator** [comment]
Seems to work fine on my side, too - nice work :)

**Comment by the-sane** [comment]
Added in the latest release. Thanks everyone!
