### ISSUE TITLE
Won't download the correct vcrun2019 file

### ISSUE THREAD

**Issue by Mindst0rms** [starcitizen-lug/lug-helper#45]
Installing on pop_os 22.04, the download for vc_redist.x86.exe is redirected to the wrong link and causes the installer to fail.
Updating to the latest winetricks release and downloading from the original link before redirect fixes the issue for me.
![unknown](https://user-images.githubusercontent.com/52639328/194759356-6e96847d-e614-49f9-bebf-13fe354d003b.png)

**Comment by the-sane** [comment]
Thanks for the heads up about this. I think it's an issue upstream somewhere, either with winetricks or microsoft's url redirect. All we do in our install json is request vcrun2019, then wine handles that fetching part on its own. If someone over in the tech support discord comes up with a workaround, I'll add that info here and reopen this.

**Comment by Termuellinator** [comment]
301 looks like it has been moved by MS - so probably best to see if it is already reported on wine/winetricks.
