### ISSUE TITLE
Flatpak detection issue when multiple versions of Lutris flatpak are installed

### ISSUE THREAD

**Issue by jibsaramnim** [starcitizen-lug/lug-helper#48]
- Related to #44.

First; thanks so much for doing all this work! It's great to be able to continue using your fantastic tool even after switching to Fedora Silverblue and going with more flatpak based installs! :)

---

As it turns out, Flatpak has an odd way of handling `flatpak info` if two (or more) versions of an application are installed. Instead of returning both, or a default, it instead returns an error:

```bash
~ ❯❯❯ flatpak info net.lutris.Lutris
error: Multiple branches available for net.lutris.Lutris, you must specify one of: net.lutris.Lutris/x86_64/stable, net.lutris.Lutris/x86_64/beta
```

I stumbled upon this after installing the Lutris beta as it has upgraded the runtime to 22.08, required to get Gamescope working again. I did not remove the stable release as doing that makes it want to also remove the Gamescope package, and because I only temporarily use the beta to have working Gamescope while waiting for a new Lutris release.

I honestly kind of feel like Flatpak's way of handling this is a bit wonky, but that aside, if you would want to consider supporting this use-case too, perhaps it's as simple as testing for both `net.lutris.Lutris/x86_64/stable` and `net.lutris.Lutris/x86_64/beta`, taking either one's positive result as Lutris being installed might be enough?

Something like:

```patch
diff --git a/lug-helper.sh b/lug-helper.sh
index 9c81fdc..e590f43 100755
--- a/lug-helper.sh
+++ b/lug-helper.sh
@@ -901,7 +901,7 @@ lutris_detect() {
 
     # Detect flatpak lutris
     if [ -x "$(command -v flatpak)" ]; then
-        flatpak info net.lutris.Lutris >/dev/null 2>&1
+        [ flatpak info net.lutris.Lutris/x86_64/stable >/dev/null 2>&1 || flatpak info net.lutris.Lutris/x86_64/beta >/dev/null 2>&1 ]
         if [ "$?" -eq 0 ]; then
             lutris_installed="true"
             lutris_flatpak="true"
```

**Comment by the-sane** [comment]
> I honestly kind of feel like Flatpak's way of handling this is a bit wonky

I'd say more than a bit wonky. This whole process of adding flatpak support has sorta made me hate flatpaks, not gonna lie.

:thinking: But anyway, we should handle this scenario if we can. Based on this, I'm starting to wonder if `flatpak info` isn't the best way of doing this. Can you look around to see if there's a better way for us to detect whether Lutris is installed via flatpak?

As you're aware, we use `command -v` for the native install. It's simple and returns true regardless of what version of the application is installed. We ideally want something similar for flatpak to avoid having to specify individual channels or versions like this. While it may work right now, it's not completely future-proof if something changes or they decide to restructure their channels. As an example, say they decide to switch to multi-arch releases and remove the x86_64 from their naming schemes. That would break this.

I'd really appreciate some research help in finding a better way to do this test.

**Comment by the-sane** [comment]
Alright, this should be fixed with https://github.com/starcitizen-lug/lug-helper/commit/2343bfb7338cbba07f20a3c362badef0486f27b6

If you can find a better way to do this, feel free to re-open and let me know. Thanks!

**Comment by jibsaramnim** [comment]
Nice, that's an even better catch-all way yes, clever! I am honestly not sure if there's a better way offered by Flatpak, it just seems that they need you to be _very_ specific if more than one result can be returned, rather than listing out these results. 

Looking at `flatpak list` might be the cleanest way, and just grepping for `Lutris` should be safe enough, one would assume.

Cheers!
