### ISSUE TITLE
Install does not finish under specific conditions

### ISSUE THREAD

**Issue by AmethystNightshade** [starcitizen-lug/lug-helper#49]
When I run the script without the Glorious Eggroll SC version in the JSON already installed and I do not click the OK box for "the install will now continue in lutris" before continuing the install, it only installs the GE-SC runner and nothing else. If I either already have the GE-SC runner installed or I click OK in the lug helper before continuing, it installs completely.

I am running the 2.0 version of the lug-helper on the latest git version of lutris from the AUR ("0.5.12.beta1.r24.g2f474ffe-1" currently)

**Comment by the-sane** [comment]
It's really strange that the message box you're referring to would affect the install process.

@beniwtv, do you have any ideas about why that would be the case?

https://github.com/starcitizen-lug/lug-helper/blob/2343bfb7338cbba07f20a3c362badef0486f27b6/lug-helper.sh#L1914-L1924

**Comment by AmethystNightshade** [comment]
if my memory serves me right, i don't think lutris opened until you clicked the ok box in past versions, but i could be wrong

**Comment by the-sane** [comment]
It should be opening simultaneously or slightly delayed. The code above launches lutris as a detached process then continues on with the Helper script. The Helper's message box can't really get in the way of the install.

The part you mentioned where it's only installing the runner and nothing else is curious though. To figure out what's going on, I think we'd need to see some logs from when that happens. Please run lutris in debug mode with `lutris -d` and then paste the terminal output here. Thanks!

**Comment by AmethystNightshade** [comment]
I'm assuming that means having lutris open in the background with debug on while running the lug-helper script. I'm currently downloading the game rn, but will try that with a different prefix and report back once the download is done.

**Comment by the-sane** [comment]
Yes, if you launch Lutris like that first and then run the Helper install, it will connect with the existing Lutris process in debug mode. Thanks!

**Comment by AmethystNightshade** [comment]
it seems that if lutris is running during the lug-helper install, then it works. but if it is not running in the background then i run into the issues. i will modify the script to add in the debug switch to the install command. and put in those logs

**Comment by AmethystNightshade** [comment]
seems that i am not able to reproduce the issue anymore for some reason. i know that when it did happen (2 or 3 times) it would run the install, go through choose install, choose location, then continue to download and extract the GE-SC, but then just close with no prompt to download the installer and no prefix created, but it did completely install the GE-SC runner.

going to close this issue as i cannot reproduce it anymore

**Comment by the-sane** [comment]
They did have problems today where a buggy launcher was released that broke on a lot of people. I wonder if this is related? Maybe they were switching off some of their downloads temporarily while they were fixing the problem?

We have a great tech support community in our Discord/Matrix channels. I'm going to ask in there for testers to help try to reproduce this just in case it is something real that we can investigate.

**Comment by beniwtv** [comment]
Seems strange indeed, also could be that Lutris crashed while installing?
