### ISSUE TITLE
Starcitizen.exe in system monitor but nothing happens

### ISSUE THREAD

**Issue by 0xDPE** [starcitizen-lug/lug-helper#50]
When I press launch the eac launcher pops up for one sec then disappears. The launcher says the game is running and the system manager says StarCitizen.exe is running. However, there is nothing. Not in the system tray not anywhere. Should I wait? or what should I do?

**Comment by the-sane** [comment]
Hi! We have a troubleshooting section on our wiki and also links to our Discord/Matrix channels. I'd recommend asking for help in our tech support Discord channel. We have plenty of penguins there who can help out.

Wiki is here: https://github.com/starcitizen-lug/information-howtos/wiki
Discord: https://discord.gg/meCFYPj
Matrix (bridged to discord: https://matrix.to/#/#SCLUG:matrix.org

I'll close this issue as this is really for problems with our Helper package.
