### ISSUE TITLE
Lutris fails to create wine runner directory

### ISSUE THREAD

**Issue by the-sane** [starcitizen-lug/lug-helper#63]
![screenshot of error](https://media.discordapp.net/attachments/679838020454842411/1139949486274265098/image.png)

Supposedly lutris won't create this directory unless it downloads the runner itself.

Options:
- Upstream bug to lutris
- Skip the error and `mkdir -p` these directories instead

**Comment by Termuellinator** [comment]
At which point does that happen? When running the Lutris installer?
I'm not sure how often it should 'normally' happen that Lutris might encounter something like that, so not sure if that's really that much of relevance for upstream? Can't hurt to make them aware of course.

**Comment by the-sane** [comment]
Seems like it only happens at initial install, though I'm not sure why Lutris has suddenly decided to not download the default runner for some people.

Either way, I agree, not really an upstreamable bug since Lutris will go ahead and make those directories when it needs to. It's only a problem for us when someone tries to install a runner after initial setup. I'm going to go with the mkdir option instead.

**Comment by the-sane** [comment]
Looks like I'm already creating those directories in the install function, so this error is completely unnecessary. It must have been left over from a time before I refactored the download code to handle things more safely.

Fixed in https://github.com/starcitizen-lug/lug-helper/commit/2850128ec4de838480ff60ccbbc8e668239f5247
