### ISSUE TITLE
Star citizen required DirectX feature level of 11.1 as minimum..

### ISSUE THREAD

**Issue by alepefe** [starcitizen-lug/lug-helper#66]
![Proof](https://github.com/starcitizen-lug/lug-helper/assets/96791505/9c99da45-7921-45e6-95b7-5ac79138f34e)

**Comment by alepefe** [comment]
It works with DXVK < 2.0.0

**Comment by the-sane** [comment]
Hi! That’s a warning that Star Citizen itself is throwing and we don’t have any control over that. I’m pretty sure you can just hit okay and ignore it.

If you’re having any issues running the game, I’d recommend asking for help in our Discord tech support channel. The link is on our [wiki](https://github.com/starcitizen-lug/knowledge-base/wiki). It’s also bridged to our Matrix space if you don’t want to use Discord.
