### ISSUE TITLE
install error:  command exited with code 256

### ISSUE THREAD

**Issue by paintedrealms** [starcitizen-lug/lug-helper#77]
installed all prereqs ie, lutris, winetricks, wine, etc.  passes checks
told lug helper to start installing star citizen.  a screen with a lot of orange writing shows that it is downloading and installing various things too fast for me to see but then that all goes away with code 256.  I dont have any more data to go off of but it would be handy if you made it so the info stays.

a rerun with lutris -d and running star citizen installfrom lug-helper:

2024-01-15 17:56:15,363: Command 'vulkaninfo' not found on your system
2024-01-15 17:56:15,692: The Battle.net source is unavailable because Google protobuf could not be loaded: No module named 'google'
INFO     2024-01-15 17:56:15,810 [application.do_command_line:479]:Starting Lutris 0.5.15
INFO     2024-01-15 17:56:15,811 [startup.get_drivers:54]:Using NVIDIA drivers 545.29.06 for x86_64
INFO     2024-01-15 17:56:15,811 [startup.get_drivers:58]:GPU: NVIDIA GeForce RTX 3080
INFO     2024-01-15 17:56:15,811 [display.display_gpu_info:78]:GPU: 10DE:2206 10DE:1467 (nvidia drivers)
INFO     2024-01-15 17:56:15,811 [display.display_gpu_info:78]:GPU:   (simple-framebuffer drivers)
ERROR    2024-01-15 17:56:15,811 [startup.check_libs:89]:i386 libgnutls.so.30 missing (needed by gnutls)
WARNING  2024-01-15 17:56:15,845 [system.get_name:705]:vulkaninfo not available, unable to list GPUs
WARNING  2024-01-15 17:56:15,845 [system.get_name:705]:vulkaninfo not available, unable to list GPUs
DEBUG    2024-01-15 17:56:15,917 [xrandr._get_vidmodes:16]:Retrieving video modes from XrandR
DEBUG    2024-01-15 17:56:16,149 [lutris.get_missing_game_ids:206]:Checking for missing games
ERROR    2024-01-15 17:56:16,162 [style_manager._call_cb:87]:Error reading color-scheme: g-dbus-error-quark: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface “org.freedesktop.portal.Settings” on object at path /org/freedesktop/portal/desktop (19)
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/lutris/style_manager.py", line 80, in _call_cb
    values = obj.call_finish(result)
             ^^^^^^^^^^^^^^^^^^^^^^^
gi.repository.GLib.GError: g-dbus-error-quark: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface “org.freedesktop.portal.Settings” on object at path /org/freedesktop/portal/desktop (19)
INFO     2024-01-15 17:56:25,789 [application.do_command_line:479]:Starting Lutris 0.5.15
INFO     2024-01-15 17:56:25,790 [startup.get_drivers:54]:Using NVIDIA drivers 545.29.06 for x86_64
INFO     2024-01-15 17:56:25,790 [startup.get_drivers:58]:GPU: NVIDIA GeForce RTX 3080
INFO     2024-01-15 17:56:25,790 [display.display_gpu_info:78]:GPU: 10DE:2206 10DE:1467 (nvidia drivers)
INFO     2024-01-15 17:56:25,790 [display.display_gpu_info:78]:GPU:   (simple-framebuffer drivers)
ERROR    2024-01-15 17:56:25,790 [startup.check_libs:89]:i386 libgnutls.so.30 missing (needed by gnutls)
WARNING  2024-01-15 17:56:25,814 [system.get_name:705]:vulkaninfo not available, unable to list GPUs
WARNING  2024-01-15 17:56:25,814 [system.get_name:705]:vulkaninfo not available, unable to list GPUs
DEBUG    2024-01-15 17:56:25,815 [__init__.read_script:23]:Loading script(s) from /usr/share/lug-helper/lutris-starcitizen.json
DEBUG    2024-01-15 17:56:25,842 [application.show_window:392]:Showing window InstallerWindowstar-citizen
DEBUG    2024-01-15 17:56:32,259 [xrandr._get_vidmodes:16]:Retrieving video modes from XrandR
INFO     2024-01-15 17:56:34,288 [api.get_default_runner_version_info:204]:Getting runner information for wine (version: wine-ge-8-25-x86_64)
DEBUG    2024-01-15 17:56:34,288 [http._request:88]:GET https://lutris.net/api/runners/wine
DEBUG    2024-01-15 17:56:34,701 [wine.get_installer_runner_version:786]:Default wine version is wine-ge-8-25
DEBUG    2024-01-15 17:56:34,736 [installerwindow.on_files_prepared:612]:Installer doesn't require files
INFO     2024-01-15 17:56:34,736 [installerwindow.launch_installer_commands:670]:Launching installer commands
DEBUG    2024-01-15 17:56:34,736 [interpreter._iter_commands:317]:Installer command: {'task': {'arch': 'win64', 'name': 'create_prefix', 'prefix': '$GAMEDIR'}}
INFO     2024-01-15 17:56:34,773 [wine.create_prefix:97]:Creating a win64 prefix in /home/stephen/Games/star-citizen
DEBUG    2024-01-15 17:56:34,773 [system._execute:104]:Executing /home/stephen/.local/share/lutris/runners/wine/wine-ge-8-25-x86_64/bin/wineboot
DEBUG    2024-01-15 17:56:34,773 [system._execute:110]:WINEARCH=win64 WINEPREFIX=/home/stephen/Games/star-citizen WINEDLLOVERRIDES=winemenubuilder= WINE_MONO_CACHE_DIR=/home/stephen/.local/share/lutris/runners/wine/wine-ge-8-25-x86_64/mono WINE_GECKO_CACHE_DIR=/home/stephen/.local/share/lutris/runners/wine/wine-ge-8-25-x86_64/gecko
INFO     2024-01-15 17:56:35,870 [wine.create_prefix:149]:win64 Prefix created in /home/stephen/Games/star-citizen
DEBUG    2024-01-15 17:56:35,875 [interpreter._iter_commands:317]:Installer command: {'task': {'app': 'arial vcrun2019 win10', 'arch': 'win64', 'name': 'winetricks', 'prefix': '$GAMEDIR'}}
DEBUG    2024-01-15 17:56:46,746 [command.on_stop:219]:Process 8663 has terminated with code 0
DEBUG    2024-01-15 17:56:46,980 [commands._monitor_task:441]:Return code: 0
DEBUG    2024-01-15 17:56:46,980 [interpreter._iter_commands:317]:Installer command: {'task': {'arch': 'win64', 'args': '/S', 'executable': 'client', 'name': 'wineexec', 'prefix': '$GAMEDIR'}}
WARNING  2024-01-15 17:56:47,155 [runner.game_config:92]:Accessing game config while runner wasn't given one.
WARNING  2024-01-15 17:56:47,155 [runner.game_config:92]:Accessing game config while runner wasn't given one.
ERROR    2024-01-15 17:56:47,155 [wine.game_exe:616]:The game doesn't have an executable
DEBUG    2024-01-15 17:56:47,909 [command.on_stop:219]:Process 9884 has terminated with code 256
DEBUG    2024-01-15 17:56:48,156 [commands._monitor_task:441]:Return code: 256
ERROR    2024-01-15 17:56:48,156 [errors.__init__:18]:Command exited with code 256
ERROR    2024-01-15 17:56:48,156 [exception_backstops.error_wrapper:81]:Error handling timeout function: Command exited with code 256
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/lutris/exception_backstops.py", line 79, in error_wrapper
    return handler(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/lutris/installer/commands.py", line 443, in _monitor_task
    raise ScriptingError(_("Command exited with code %s") % command.return_code)
lutris.installer.errors.ScriptingError: Command exited with code 256
INFO     2024-01-15 17:58:31,899 [interpreter.revert:396]:Cancelling installation of Star Citizen
DEBUG    2024-01-15 17:58:31,951 [wine.winekill:168]:Killing all wine processes: ['/home/stephen/.local/share/lutris/runners/wine/wine-ge-8-25-x86_64/bin/wineserver', '-k']
DEBUG    2024-01-15 17:58:31,951 [wine.winekill:169]:	Wine prefix: /home/stephen/Games/star-citizen
DEBUG    2024-01-15 17:58:31,951 [wine.winekill:170]:	Wine arch: win64
DEBUG    2024-01-15 17:58:31,952 [wine.winekill:176]:Waiting for wine processes to terminate
DEBUG    2024-01-15 17:58:31,952 [wine.winekill:192]:Done waiting.
DEBUG    2024-01-15 17:58:31,952 [system.delete_folder:387]:Deleting folder /home/stephen/.cache/lutris/installer/star-citizen
DEBUG    2024-01-15 17:58:31,953 [application.on_app_window_destroyed:419]:Removed window InstallerWindowstar-citizen
INFO     2024-01-15 17:58:50,312 [application.do_shutdown:1122]:Shutting down Lutris

**Comment by the-sane** [comment]
Hey there!

The scrolling text that you see is Lutris’ install process that we connect to. We don’t have any control over that part, but Lutris does log all that. The code 256 is a fairly generic code that can mean a lot of things. Your best bet is going to be to ask for help in our Discord tech support channel. It’s bridged to Matrix if you don’t want to use Discord. We have plenty of smart folks over there who can help out. 

The wiki is here, with links to our Discord and troubleshooting guide:
https://github.com/starcitizen-lug/knowledge-base/wiki

I’m going to close this issue as it’s not a problem with our Helper tool.

**Comment by paintedrealms** [comment]
Hello,  your right the discord had the solution which was to downgrade lutris.  However a better solution may require patience.  Version 0.5.15 has issues with that prevented installers from completing.  0.5.16 has fixed those and someone else flagged 5.15 old in arcolinux aur.


Sent from my iPhone

On Jan 15, 2024, at 20:09, the Sane. ***@***.***> wrote:

﻿

Closed #77<https://github.com/starcitizen-lug/lug-helper/issues/77> as completed.
