### ISSUE TITLE
Crash when changing graphics setting to "Vulkan" in 3.23 

### ISSUE THREAD

**Issue by taksyon** [starcitizen-lug/lug-helper#82]
Using Lutris and wine, I launched the EPTU for 3.23 and I changed the new graphics setting from Direct3D to Vulkan. Lutris will still launch the RSI Launcher, but trying to launch the EPTU with this graphics setting enabled crashes the game before it launches every time.

**To Reproduce**

Install EPTU
Launch the game, and go to graphics settings and change from Direct3D to Vulkan
exit, then relaunch the game

**Expected behavior**
Expected to be able to run the game with it's new Vulkan graphics settings. 

**OS Info:**
 - Distro: Arch
 - Version: 6.8.5-arch1-1

**Additional context**
I know this is EPTU, but soon(like this weekend I think) they will be launching 3.23 update on the LIVE servers. If users change the setting to Vulkan, they may have the same problem and force a reinstall. I personally have Vulkan shaders installed on my system and I tried messing with Lutris settings, prefer system libraries, enabling the different graphics options in the 'runner settings' tab, but no dice. not sure what the problem is. 

Logs:

lutris-wrapper: Star Citizen
Started initial process 33362 from /home/tak/.local/share/lutris/runners/wine/wine-ge-8-26-x86_64/bin/wine /home/tak/Games/star-citizen/drive_c/Program Files/Roberts Space Industries/RSI Launcher/RSI Launcher.exe --locale=$INPUT_LOCALE
Start monitoring process.
fsync: up and running.
wine: RLIMIT_NICE is <= 20, unable to use setpriority safely

[316:0416/174541.175:ERROR:network_change_notifier_win.cc(143)] WSALookupServiceBegin failed with: 0
[316:0416/174541.595:ERROR:network_sandbox.cc(302)] Failed to grant sandbox access to cache directory C:\users\tak\AppData\Roaming\rsilauncher\Cache\Cache_Data: Procedure not found. (0x7F)
[316:0416/174541.595:ERROR:network_sandbox.cc(396)] Failed to grant sandbox access to network context data directory C:\users\tak\AppData\Roaming\rsilauncher\Network: Success. (0x0)
[316:0416/174541.640:ERROR:network_service_instance_impl.cc(270)] Encountered error while migrating network context data or granting sandbox access for C:\users\tak\AppData\Roaming\rsilauncher\Network. Result: 6: Success. (0x0)
[540:0416/174541.800:ERROR:network_change_notifier_win.cc(143)] WSALookupServiceBegin failed with: 0
Checking for update
Update for version 1.6.10 is not available (latest version: 1.6.10, downgrade is disallowed).
17:45:43.042 > {
 "event": "AUTHENTICATION_AUTO_LOGIN",
 "data": {}
}
17:45:43.043 > {
 "event": "AUTHENTICATION_SUCCESSFUL",
 "data": {
  "heapAccountId": {
   "cookie": "_rsi_device",
   "key": "X-RSI-Device"
  }
 }
}
17:45:43.046 > {
 "event": "INITIALIZATION_SUCCESSFUL",
 "data": {}
}
17:45:43.366 > "[Error] getGameClientReleaseObject - {\"code\":\"ERR_INVALID_ARG_TYPE\"}"
17:45:43.367 > {
 "event": "SELECT_GAME_SUCCESSFUL",
 "data": {
  "platform": "prod",
  "gameId": "SC",
  "channelId": "LIVE"
 }
}
17:46:02.135 > "[Error] getGameClientReleaseObject - {\"code\":\"ERR_INVALID_ARG_TYPE\"}"
17:46:02.136 > {
 "event": "SELECT_GAME_SUCCESSFUL",
 "data": {
  "platform": "ptu",
  "gameId": "SC",
  "channelId": "EPTU"
 }
}
17:46:02.137 > "[Error] getGameClientReleaseObject - {\"code\":\"ERR_INVALID_ARG_TYPE\"}"
Checking for update
17:46:04.726 > {
 "event": "LAUNCH_GAME",
 "data": {}
}
Update for version 1.6.10 is not available (latest version: 1.6.10, downgrade is disallowed).
17:46:05.179 > {
 "event": "LAUNCH_GAME_READY",
 "data": {
  "platformId": "ptu",
  "gameId": "SC",
  "channelId": "EPTU",
  "heapAccountId": {},
  "gameToken": "***"
 }
}
17:46:05.181 > "Launching Star Citizen EPTU from (C:\\Program Files\\Roberts Space Industries\\StarCitizen\\EPTU)"
17:46:05.181 > "Deleting C:\\Program Files\\Roberts Space Industries\\StarCitizen\\EPTU\\loginData.json for EPTU"
17:46:22.898 > "Star Citizen process exited abnormally (code: 732819469) : Command failed: C:\\Program Files\\Roberts Space Industries\\StarCitizen\\EPTU\\StarCitizen_Launcher.exe -no_login_dialog -envtag PTU --client-login-show-dialog 0 --services-config-enabled 1 --system-trace-service-enabled 1 --system-trace-env-id ptu-sc-alpha-3230-9142594 --grpc-client-endpoint-override https://ptu-sc-alpha-3230-9142594.test1.cloudimperiumgames.com:443\n"
17:46:22.899 > "Setting timeout to delete login data for EPTU (300 seconds)"
17:51:22.901 > "Clearing login data removal timeout for EPTU"
17:51:22.902 > "Deleting C:\\Program Files\\Roberts Space Industries\\StarCitizen\\EPTU\\loginData.json for EPTU"
Checking for update
Update for version 1.6.10 is not available (latest version: 1.6.10, downgrade is disallowed).

**Comment by mactan-sc** [comment]
Hey there! Your best bet is going to be to ask for help in our Discord tech support channel. It's bridged to our Matrix space if you don't have or want to use Discord. The links are on our wiki: https://starcitizen-lug.github.io/

You'll find a lot of helpful penguins in there. I'm going to close this issue since it's a game issue with the new beta vulkan graphics mode
