### ISSUE TITLE
Switching SC to vulkan mode makes it so that the game doesn't load

### ISSUE THREAD

**Issue by ageisen2000** [starcitizen-lug/lug-helper#85]
**Describe the bug**
Switching SC to vulkan mode makes it so that the game doesn't load

**To Reproduce**
1. Open the game
2. switch to the vulkan graphics api
3. restart the game
4. try to launch -- nothing happens

**Expected behavior**
The game should launch. I'd like if there was some tooltips or instructions for how to play with the new Vulkan API mode for SC

**OS Info:**
 - Distro: EndeavourOS (Arch)

**Additional context**
I'm mostly looking for additional help on getting this working through the LUG helper tool. The game does run on DirectX11.

**Comment by Termuellinator** [comment]
Hey there! Your best bet is going to be to ask for help in our Discord tech support channel. It's bridged to our Matrix space if you don't have or want to use Discord. The links are on our wiki: https://starcitizen-lug.github.io/.
I'm going to close this issue as this probably isn't directly related to the helper :)

**Comment by ageisen2000** [comment]
@Termuellinator, thanks for the quick response and links.

I wasn't asking for tech support, this was an issue for updating the tool to support vulkan mode. CIG has mentioned that they will be removing dx11 asap

**Comment by Termuellinator** [comment]
To my knowledge, vulkan mode should work (besides some glitches that are not exclusive to linux) with the current setup. Should your troubleshooting reveal something that has to be changed in the installer or some other general thing, we're of course happy to hear back and implement that! :)

**Comment by ageisen2000** [comment]
Thank you. That's all I needed to hear. I'll spend more time debugging and let you know if I find something missing
