### ISSUE TITLE
installing star citizen on the 2.0 launcher 

### ISSUE THREAD

**Issue by harryman11** [starcitizen-lug/lug-helper#90]
**Describe the bug**
installing star citizen on the 2.0 launcher throws a error code 2000 and not letting you install no matter what , this makes you download the 1.6 launcher witch on october 1st is no longer going to be possable , this has only started happining since 3.23-3.24

**To Reproduce**
1. sett up as normal 
2. sighn in to rsl 
3. press install 
4. then you get error 200 
**Expected behavior**
it should let you install but throws the code and rqires you to pre install the file and drag it in 

**OS Info:**
 - Distro: zoron 17.6
 - Version if applicable newest

**Comment by the-sane** [comment]
Hey there! We have migration instructions for the 2.0 launcher available over on [our wiki](https://github.com/starcitizen-lug/knowledge-base/wiki#news). Our current recommendation is to wait, as there are still some issues that need to be sorted out.

If you need further help, you can ask over on our Discord. Links to that are also available on our wiki.

I'm going to go ahead and close this issue as it's not related to a bug in our Helper tool.
