### ISSUE TITLE
Ugly solution to issue 72

### ISSUE THREAD

**Issue by crocodile13** [starcitizen-lug/lug-helper#93]
If you're interested, you can check out the small addition I made to resolve [issue 72](https://github.com/starcitizen-lug/lug-helper/issues/72). I'm on Ubuntu 22. I didn't create a merge request because I don't really understand the root cause of the problem, and the solution is completely empirical and not clean.
It is this [repo.](https://github.com/crocodile13/lug-helper)

Nb: I feel so stupid, I made a mistake and just posted that on the Lutris project... :'(

**Comment by the-sane** [comment]
I've re-opened https://github.com/starcitizen-lug/lug-helper/issues/72 since all the information is over there. Please see my latest comment if you're willing to help get this resolved. I'm closing this one in favor of that issue.
