### ISSUE TITLE
Running lug-helper.sh does nothing

### ISSUE THREAD

**Issue by pfaca** [starcitizen-lug/lug-helper#94]
When trying to lunch lug-helper.sh nothing happens. No errors.

![image](https://github.com/user-attachments/assets/7209d6a6-4886-4e4d-b1db-7f054528555f)

I've tried installing it from AUR, but the result its the same.

**OS Info:**
 - Distro: Arch
 - Version 3.0.1

**Additional context**
I have all the dependencies installed: bash, coreutils, curl, polkit and zenity

**Comment by Termuellinator** [comment]
You could try running it with `bash +x ./lug-helper.sh` to see if that yields some indication on where it fails.
Other than that, see if zenity works correctly with `zenity --info`.

Besides the troubleshooting:
If you're fine with CLI, you could run the script with option `-g` to use CLI even when zenity is installed.

**Comment by pfaca** [comment]
Running bash `+x ./lug-helper.sh` same thing has previously.

Running `./lug-helper.sh -g` does indeed work.

`zenity --info` gives some errors:

**Comment by the-sane** [comment]
This is the error you'll want to google: `Error 71 (Protocol error) dispatching to Wayland display`

From a brief look, it looks like it could be an nvidia driver problem and may end up causing you issues with other apps as well.

As far as our Helper goes though, I'd recommend using the non-gui option for now. There's not much we can do about an nvidia problem on our end, so I'm closing this issue. If you need further help with the nvidia problem, our discord link is on [the wiki](https://github.com/starcitizen-lug/knowledge-base/wiki) and you can ask for help in our tech support channel.

**Comment by pfaca** [comment]
I'm using an AMD GPU, but I'll try searching your suggestion.

Nevertheless it works from CLI, and that is fine by me.

Thanks for the help.

**Comment by the-sane** [comment]
@pfaca As a quick side note, if you're able to get me the error code returned by zenity, I can catch it in the Helper and print a more useful error message for situations like this:

```
zenity --info
echo "$?"
```

**Comment by pfaca** [comment]
![image](https://github.com/user-attachments/assets/491cc906-1845-4795-8b6d-e5bddad254e8)

**Comment by the-sane** [comment]
Thanks! I'll see what I can do with that.

**Comment by the-sane** [comment]
@pfaca Can you do me one last favor and try the same as above but with the `zenity --version` command? Then get its return code with `echo "$?"`

**Comment by pfaca** [comment]
Ok, so tried messing with the GNOME/GTK application style in KDE Settings, and after rebooting now the GUI is working.

**Comment by pfaca** [comment]
Ok, so tried messing with the GNOME/GTK application style in KDE Settings, and after rebooting the GUI is working.

![image](https://github.com/user-attachments/assets/50206cba-2c50-4225-b4a4-d6a3949bcc08)


```
zenity --info
echo "$?"
```
![image](https://github.com/user-attachments/assets/6cb3b711-e02f-44d8-8d20-330b0da7a55b)
Now returns 0.

The same thing for `--version`, so I don´t know if it is any help...
```
zenity --version   
echo "$?"
```
![image](https://github.com/user-attachments/assets/69dd48ef-eedf-4693-9044-cf65b317e239)

**Comment by the-sane** [comment]
@pfaca If you're willing to undo your fixes to break zenity again, I'd need the return code from when it isn't working.

**Comment by pfaca** [comment]
No problem. Just give me a minute, I have to find what fixed it.

**Comment by pfaca** [comment]
So what fixed it was not GNOME/GTK in KDE settings.

**Comment by pfaca** [comment]
@the-sane So what fixed it was not GNOME/GTK in KDE settings.

I had to add a line to the environment file in /etc/.
`GSK_RENDERER=ngl`

![image](https://github.com/user-attachments/assets/626fe6f1-ff23-400f-837e-cd52bd327518)

Hope it helps!

**Comment by the-sane** [comment]
Thank you
