### ISSUE TITLE
LUG Helper fails to open wayland window on KDE Plasma 6.2.3

### ISSUE THREAD

**Issue by spacekookie** [starcitizen-lug/lug-helper#97]
**Describe the bug**
When running `lug-helper.sh` I get the following error message:

```
Gdk-Message: 17:07:19.720: Error 71 (Protocol error) dispatching to Wayland display.
```

**To Reproduce**
1. Clone the repo
2. Run `lug-helper.sh` (on KDE Plasma 6.2 wayland)

**Expected behavior**
It opens

**OS Info:**
 - Distro: Arch Linux
 - Desktop: KDE Plasma 6.2.3

**Comment by the-sane** [comment]
Hey there! Sounds like there's something wrong with your Zenity install or configuration. You can confirm this and possibly get more info by running zenity commands in your terminal. For example, see what `zenity --version` and `zenity --info` outputs.

As a workaround, run the Helper without the zenity gui. `./lug-helper.sh --no-gui`

**Comment by spacekookie** [comment]
Hey! Thanks for the quick reply.

`zenity` seems to be installed, but `--info` fails too:

```
 ❤  (tempest) ~/P/_/lug-helper> zenity --version                                                                                                                                                                                             
4.0.3
 ❤  (tempest) ~/P/_/lug-helper> zenity --info                                                                                                                                                                                                
Gdk-Message: 17:18:07.811: Error 71 (Protocol error) dispatching to Wayland display.
(1)  ❤  (tempest) ~/P/_/lug-helper>    
```

I can use the --no-gui setting for now but it would be nice if I could get the UI fixed too :P

**Comment by the-sane** [comment]
Someone else had a similar issue not too long ago. You may find some useful info in this issue to help you debug your configuration problems: https://github.com/starcitizen-lug/lug-helper/issues/94

**Comment by the-sane** [comment]
Closing this issue since it's likely a zenity configuration issue and a workaround already exists. Feel free to re-open if you find any new information that isn't already mentioned in the linked thread above.
