### ISSUE TITLE
Can't launch the launcher

### ISSUE THREAD

**Issue by mouarfff** [starcitizen-lug/lug-helper#98]
Bazzite OS legion go version
Legion Go
Lutris from Flatpaks
Lug-Helper last version from here

The laucnher installation is ok, but when the launcher just don't launch at all

error message :

"Started initial process 18652 from /usr/bin/ptyxis -e /home/steamdeck/.cache/lutris/run_in_term.sh
Start monitoring process.
Unknown option -e
Monitored process exited.
Initial process has exited (return code: 256)
All processes have quit
Exit with return code 256"

**Comment by Termuellinator** [comment]
Heyho! As this is (probably) not directly related to the helper, i think asking for help in our Discord tech support channel is the better option. There are a lot of really helpful folks there. It's also bridged to our Matrix space if you don't have or want to use Discord. The links are on our wiki: https://starcitizen-lug.github.io/

I'm closing this issue for now - but if your investigations yield something that really is related to the launcher or is a general problem that we can address here, please let us know! :)
